apiVersion: v1
kind: Service
metadata:
  name: mall-admin-web
  namespace: mall-swarm
spec:
  type: ClusterIP
  selector:
    app: mall-admin-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
