apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-monitor
  namespace: mall-swarm
  labels:
    app: mall-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-monitor
  template:
    metadata:
      labels:
        app: mall-monitor
    spec:
      containers:
        - name: mall-monitor
          # 指定Docker Hub中的镜像地址
          image: goharbor.com/mall-swarm/mall-monitor:latest
          resources:
            limits:
              cpu: "500m"
              memory: 500Mi
            requests:
              cpu: "100m"
              memory: 100Mi
          ports:
            - containerPort: 8101
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            # 指定Nacos地址
            - name: spring.cloud.nacos.discovery.server-addr
              value: http://nacos-0.nacos-headless.default:8848
            - name: spring.cloud.nacos.config.server-addr
              value: http://nacos-0.nacos-headless.default:8848
      #     volumeMounts:
      #       - mountPath: /var/logs
      #         name: log-volume
      # volumes:
      #   - name: log-volume
      #     hostPath:
      #       path: /mydata/app/mall-monitor/logs
      #       type: DirectoryOrCreate
