apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mall-swarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: goharbor.com/devops/mysql:5.7
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
          name: mall-swarm-mysql
          env:
            - name: MYSQL_DATABASE
              value: "mall"
            - name: MYSQL_ROOT_PASSWORD
              value: "swarm123"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: swarm-mysql
          ports:
            - containerPort: 3306
              name: "mysql-port"
      volumes:
        - name: swarm-mysql
          hostPath:
            path: /var/lib/swarm/mysql
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mall-swarm
  labels:
    name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      name: "mysql"
  selector:
    app: mysql
