apiVersion: v1
kind: Pod
metadata:
  name: cpu-consumer
spec:
  containers:
    - name: sleep-loop
      image: busybox
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "500m"
          memory: 100Mi
      args:
        - /bin/sh
        - -c,
        - i=0; while true; do i=$((i+1)); sleep 1; done
