apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: mall-swarm
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
      name: kibana-manage
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: mall-swarm
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: goharbor.com/devops/kibana:7.17.3
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: ELASTICSEARCH_URL
              value: http://es-cluster-0.elasticsearch.mall-swarm.svc.cluster.local:9200
          ports:
            - containerPort: 5601
              name: kibana-manage
